### ISSUE TITLE
Save on deactivate

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#164] opened 2018-05-01 20:37 UTC
Add a new setting (default off): if enabled, when application loses focus - current file is saved, unless it's unnamed (wasn't yet saved). This is fully equivalent to calling File > Save manually.

Add corresponding menu item `Save On Lose Focus` under File > Read Only. When called, shows a similar dialog to File Change Notification except there are 2 radio buttons only: `Don't save` and `Save`. `Reset if a new file is opened` is also present (if checked - when new file is opened or created, sets Don't save automatically). When Save is active, that menu item displays a checkbox. It's generally similar to File Change Notification.

Also, rename item Read Only to Read-Only.

**Comment by cshnik** [comment] 2018-05-04 17:39
> When called, shows a similar dialog to File Change Notification except there are 2 radio buttons only: Don't save and Save.

> It's generally similar to File Change Notification.

FCN configuration dialog allow user to select required mode when the feature is active (Display message/Auto-reload(unmodified)) or disable it.
Implementation of the same configuration dialog looks excess for "Save On Lose Focus" feature since it is assumed to have only 2 modes: ON/OFF. It should have the same switching mechanism as "Insert Tabs as Spaces", "Auto Indent Text", "Reuse Window": corresponding menu item has(has no) checkmark when feature is ON(OFF). There is no additional tuning available for these features and the same UI behavior shared for them will allow to keep application UI clean and smooth.
Please confirm if configuration dialog with 2 radio buttons is still required.

**Comment by ProgerXP** [comment] 2018-05-04 18:05
> Implementation of the same configuration dialog looks excess for "Save On Lose Focus" feature since it is assumed to have only 2 modes: ON/OFF. 

No, it also has this checkbox: Reset if a new file is opened
That's why either a dialog is necessary or a 2 level menu which is less convnient.

**Comment by cshnik** [comment] 2018-05-04 18:18
> No, it also has this checkbox: Reset if a new file is opened
That's why either a dialog is necessary or a 2 level menu which is less convnient.

OK. Just a thought, "Esc Key Function" and "Evaluate Math Expressions" looks near the same:
![image](https://user-images.githubusercontent.com/8019354/39645265-e6b010ea-5001-11e8-8f5f-45e7c44d8fed.png)
Save On Lose Focus>
``Disabled``
``Enabled``
``Reset on file open``

**Comment by ProgerXP** [comment] 2018-05-04 18:37
On the second thought, rename 2nd to Enabled ~~permanently~~

**Comment by cshnik** [comment] 2018-05-14 18:10
Done.

**Comment by ProgerXP** [comment] 2018-05-16 18:12
>> when application loses focus - current file is saved, **unless it's unnamed** (wasn't yet saved). 

The purpose is to avoid producing dialogs (interactivity) on deactivation.

**Comment by cshnik** [comment] 2018-05-16 19:43
> >> when application loses focus - current file is saved, **unless it's unnamed** (wasn't yet saved). 

> The purpose is to avoid producing dialogs (interactivity) on deactivation.

Are there any problems with current implementation of this feature? Please provide details on the cases which are not correctly addressed (if any).


> What's the purpose of bSkipFirstReset here?

The point is: ``n2e_ResetSaveOnLoseFocus()`` is called only from generic ``_LoadFile()``  method which is always used to create new/open existing file. Application's initialization may cause the very first call to ``_LoadFile()`` from ``InitInstance()`` to reset feature's state loaded from INI. I.e.: it will be impossible to start application with "Save on lose focus" feature set to "Enabled until a new file is opened" because it will be automatically switched to "Disabled" without actual user activity.

**Comment by ProgerXP** [comment] 2018-05-19 13:43
> Are there any problems with current implementation of this feature? Please provide details on the cases which are not correctly addressed (if any).

I'd like the program not to produce any dialogs when it loses focus. This would be a strange behavior. 

One case when it gets in a way is drag & drop a file onto the program's window - if the editor had unnamed file that would produce a Save dialog and instead of dropping the file onto the editor (and opening it) I'd drop it onto the Save dialog (and move the file to another location). 

Another example is when there's already a child window opened (like an Open dialog or Tab settings) - if file is unsaved, this brings up second modal (!) child window on top of others. 

So as a rule, when saving involves interactive operations - don't save-on-deactivate.

**Comment by cshnik** [comment] 2018-05-21 18:31
Fixed. "Save on Lose Focus" no longer executed for unnamed file to prevent SaveFile-dialog popup.

**Comment by cshnik** [comment] 2018-05-22 15:20
> IsWindowVisible() check was removed? Why?

File changes should be saved if "Save on deactivate"-feature is enabled even if main window is already hidden (before the actual application quit).

>  `+          bModified = FALSE;`

Removed.

> Is it possible for FileSave to be called twice anyway? The program is single-threaded, until FileSave finishes writing file no new message will be processed so I don't see how this block may be called while FileSave is still being executed.

There are 2 cases when FileSave() may produce MessageBoxes when trying to save modified file:
1. Read only prompt: ``%1 is read only. Save to a different file?``
2. Error prompt: ``Error saving %1. Cannot create a file when that file already exists.``

The point is: in both cases MessageBox popup does not lock dispatching of further WM_ACTIVATEAPP messages to the main window message procedure. Main window should always get "application activation notification" (WM_ACTIVATEAPP) no matter whether it have an active modal dialog or not. Please try the previous test build to check this behavior.

SaveInProgress flag was restored to exclude multiple handling of WM_ACTIVATEAPP messages within the single callstack.

**Comment by cshnik** [comment] 2018-05-22 18:09
Here are additional changes:
1. The only stable way to prevent prompt duplication (caused by FileSave() called from multiple places) is to always track FileSave() execution state (e.g. FileSave() called from WM_CLOSE handler for read only file will cause prompt ``Save changes to %1?`` popup, at this point WM_ACTIVATEAPP handler should skip its FileSave()).
2. IsWindowVisible() was returned back due to the next reasons:
I. FileSave() is always called from WM_CLOSE handler.
II. To prevent double prompt popup when closing application with modified read only file (first prompt is a result of FileSave() from WM_CLOSE handler, second one is a result of FileSave() from WM_ACTIVATEAPP handler).

**Comment by ProgerXP** [comment] 2018-05-25 20:36
Okay but you forgot to insert 2e-comments.

**Comment by cshnik** [comment] 2018-05-29 19:14
Added missing comments.

**Comment by ProgerXP** [comment] 2018-05-31 19:38
> Saving doesn't occur if any of these is true: 
> ...
> * **a child window is opened (e.g. an Open File dialog or Tab Settings)**

Since this wasn't implemented (I'm not sure how complex it is), there is a situation when the program may display two modal dialogs:

1. Open any readonly file
2. Open Tab Settings or any other dialog
3. Deactivate the app

Result: Tab Settings visible, and also a new prompt - "... readonly ... Save to another ...?" - and if Yes, this displays Save Dialog.

A quick fix is to check read-only flag and skip the save - which is necessary in any case, as it contradicts the original requirement:

>> The purpose is to avoid producing dialogs (interactivity) on deactivation.

A more complete solution would be to also check for already visible dialogs. Is it possible?

**Comment by cshnik** [comment] 2018-06-05 18:16
> A more complete solution would be to also check for already visible dialogs. Is it possible?

Fixed. Additional check for modal dialogs on top of the main window added.

**Comment by ProgerXP** [comment] 2018-06-19 18:40
I don't like `n2e_IsModalDialog()`, its checks are obscure. What if we simply check for any window on top of the main one, modal or not (so Find/Replace dialogs would also prevent autosaving from happening) - this is simpler, right?

**Comment by cshnik** [comment] 2018-08-13 20:04
> I don't like n2e_IsModalDialog(), its checks are obscure. 

n2e_IsModalDialog() was rewritten to conform this answer/recommendation: [How to discover if window is modal or not](https://stackoverflow.com/a/5784631).

**Comment by ProgerXP** [comment] 2018-08-13 20:43
It looks better now and seems to work. Now just add the check for read-only flag in the WM_ACTIVATEAPP `if` - since if this flag is set it will unconditionally produce a message box prompt ("Save to a different file?") on deactivation.

**Closed** 2018-10-15 15:37 UTC
