### ISSUE TITLE
File lock not released on open

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#100] opened 2017-03-21 19:21 UTC
1. Create new folder (with Explorer).
2. Create new text file (with Explorer).
3. Open the file with Notepad 2e.
4. Alt+G to open another file (in another folder).
5. Try to delete the folder with Explorer - you will get "file in use".
6. Close Notepad 2e.
7. Now you can delete the folder.

Why the file is not released after step 4?

**Comment by cshnik** [comment] 2017-04-10 15:13
Fixed. There was a bug related to "Open file"-dialog's behavior. Here are some points:
1. "Open file"-dialog allow user to select file to open and actually changes current directory for application (this setting will lock parent folder from deletion).
2. "Recall Previous (Alt+G)"-command reopen previously used file but ignore current directory setting.
3. The fix was to implement correct adjustment for current directory setting when reopening file.

**Comment by ProgerXP** [comment] 2017-04-10 18:35
> "Recall Previous (Alt+G)"-command reopen previously used file but remains current directory value the same.

In other words you have made it so that File | Open and Recall both change CWD?

Doesn't Notepad2 has a central function used when a file is opened, no matter via which command it is opened?

**Comment by cshnik** [comment] 2017-04-10 18:40
> In other words you have made it so that File | Open and Recall both change CWD?  

Something like that.

> Doesn't Notepad2 has a central function used when a file is opened, no matter via which command it is opened?

The fix is in _FileLoad()-function which is a general function to used load file contents.

**Comment by ProgerXP** [comment] 2017-04-10 18:42
> The fix is in _FileLoad()-function which is a general function which is used to load file contents.

But you haven't removed old call to SetCWD from File | Open (that calls _FileLoad)?

**Comment by cshnik** [comment] 2017-04-10 18:55
> But you haven't removed old call to SetCWD from File | Open (that calls _FileLoad)?  

On the contrary: _FileLoad() will cause system "File Open"-dialog to popup if it was called with empty filename. Specified changing of the current directory is in the internals of the "File Open"-dialog which is a part of the OS and it shouldn't be modified.

**Comment by ProgerXP** [comment] 2017-04-11 18:08
Okay, I forgot that standard file dialogs may change CWD themselves without an explicit call to SetCWD. This means the bug wasn't in the Notepad2's code itself per se.

However, current behaviour is even more weird. Now, in the last build, do this:
1. Create a folder "X".
2. Launch Notepad 2e, create a new file, save it to "X\Y.txt".
3. Try to delete the folder "X".

It succeeds! Why? And if I try to File | Save Notepad complains there is no such path!

How this is possible? The file's handle is supposed to be opened and locked!

**Comment by ProgerXP** [comment] 2017-04-11 18:33
Strange, I can't reproduce it after restarting Notepad 2e. Do you have ideas what has caused it?

**Comment by cshnik** [comment] 2017-04-12 18:49
1. It looks like your "faulty" scenarios relates to specific cases which may depend on the next items:
a)  switching between recent files
b) using of "File Open"-dialog to save newly created file
The default path in the "File Open"-dialog has many options which strongly depends from the current application's state. Unfortunately, I was unable to reproduce specified issue. Please provide steps to reproduce if the problem remains.  
2. Notepad2e never retains handle after file was loaded, user is able to remove currently opened file from disk drive.

**Closed** 2017-05-26 07:57 UTC
Labels: bug
