### ISSUE TITLE
Wrap mode: by column width

### ISSUE THREAD

**Issue by sergeevabc** [ProgerXP/Notepad2e#355] opened 2021-04-11 11:16 UTC
I need to type texts with fluid formatting, but looking good at a certain width,
that’s why hard line breaks near LongLine are unsuitable.  Possible recourse is
a new wrap mode “by column”, in addition to the existing “by window”. 

For example, [MadEdit][1] has it as follows

![](https://i2.imageban.ru/out/2021/04/11/f31c686faf1a4bf7c759c618e52d9c1f.png)

[1]: https://sourceforge.net/projects/madedit-mod/

**Comment by ProgerXP** [comment] 2021-04-11 14:30
It's true that Ctrl+I wraps by window size but Ctrl+Shift+W does exactly what you need.

**Comment by sergeevabc** [comment] 2021-04-11 14:34
Err… What? Ctrl+I and Ctrl+Shift+W do nothing.

**Comment by ProgerXP** [comment] 2021-04-11 14:37
Select text you want to wrap then press it.

Or your intention is to have text wrapped only visually? Then why reducing window size doesn't do the job?

**Comment by sergeevabc** [comment] 2021-04-11 14:39
Reducing window means I see other windows, therefore distraction-free typing is no longer possible.

**Comment by ProgerXP** [comment] 2021-04-11 14:56
> Reducing window means I see other windows, therefore distraction-free typing is no longer possible.

This problem should be addressed by other means. It's a specialized task meant for specialized programs, just like arranging windows, managing tabs, etc. At least, you can open another Notepad2 window in background and maximize it. Or use virtual desktops in Windows 10 where you can keep visible just one window even if you have others running in background.

> pressing Ctrl+I on selected text does nothinig

It wraps the line according to window size. If the line is not long enough, it does nothing.

> after pressing Ctrl+Shift+W on selected text I am no longer able to move cursor and type.

There was a similar bug but I can't reproduce it in the latest version or last public version (2020 release).

**Closed** 2021-04-17 20:18 UTC
