### ISSUE TITLE
Add to Favorites - selection mode

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#249] opened 2020-01-26 18:36 UTC
Extend the Alt+K dialog (Add to Favorites):

- add 4 radio buttons under the input: `Cursor position: [X] &first line [ ] l&ast line [ ] &current line [ ] &selection` where `[X]` is the default (Notepad2 behaviour) 
- `first line` works just like Notepad2: creates a new LNK file to the currently opened file
- `last line` creates a LNK file with a different command-line: `"<c:\absolute\Notepad2e.exe>" /g -1 "<c:\absolute\current.file>"`
- `current line` creates a similar LNK but with a positive `/g`
- `selection` creates a similar LNK but instead of `/g -1` it sets `/gs start:end` where `start` and `end` are current selection's positions (as displayed in the statusbar)
  - this radio button is disabled if current selection is rectangular (drag over the text area while holding Alt)
  - selection can be empty, in this case `start` = `end`
  - Notepad2 has `/g` but no `/gs` so it should be also added (both `start` and `end` must be given; `start` must be non-negative integer; `end` can be `-1` to assume EOF)
    - add `/gs` info to the help text too (`/?`)

**Comment by cshnik** [comment] 2020-02-05 19:12
Done.

**Comment by ProgerXP** [comment] 2020-02-06 10:26
- correct the accelerator: `l&ast`, not `&last` (you can't press Alt+L with one hand)
- after Alt+K with Last the internal path of the currently opened file seems to be changed - a `"` is appended (see the window's title) and, for example, F5 no longer works
- change message box type to "information" on successful creation (now is "warning")
- `/gs` - is it possible to instruct Scintilla to adjust new caret position (in any direction) so that it doesn't land in the middle of a multi-byte character? 
- `PathGetLnkPath` should be updated to retrieve the last component only so that if a fav'd shortcut links to a program with arguments (like in our case) then we open last argument, which is typically the file name (currently it tries opening the EXE file itself)

**Comment by cshnik** [comment] 2020-02-12 16:20
> * correct the accelerator: `l&ast`, not `&last` (you can't press Alt+L with one hand)

Fixed.
> * after Alt+K with Last the internal path of the currently opened file seems to be changed - a `"` is appended (see the window's title) and, for example, F5 no longer works

I was unable to reproduce specified behavior. Please provide exact steps to reproduce.
> * change message box type to "information" on successful creation (now is "warning")

Fixed.
> * `/gs` - is it possible to instruct Scintilla to adjust new caret position (in any direction) so that it doesn't land in the middle of a multi-byte character?

Fixed. Actual selection now always includes the complete right-most character from the specified range.
> * `PathGetLnkPath` should be updated to retrieve the last component only so that if a fav'd shortcut links to a program with arguments (like in our case) then we open last argument, which is typically the file name (currently it tries opening the EXE file itself)

Fixed.

**Comment by ProgerXP** [comment] 2020-02-12 17:28
> I was unable to reproduce specified behavior. Please provide exact steps to reproduce.

I found that it only happens if the pathname of the opened file contains any space. For example, open file `c:\a b c.txt`, do Alt+K, Last, OK.

**Comment by cshnik** [comment] 2020-02-12 18:35
> I found that it only happens if the pathname of the opened file contains any space. For example, open file `c:\a b c.txt`, do Alt+K, Last, OK.

Fixed.

> > Fixed. Actual selection now always includes the complete right-most character from the specified range.
> 
> That works for selection end only. If start (`/gs START:...`) is not on a character boundary - the caret is still positioned within the character.

Fixed selection start position.





> In other words, it doesn't require the path to be canonicalized. So right now it fails to extract last component if it's e.g. `notepad2.exe /gs 1:2 "%userprofie%\text.txt"`. However, it works for just `"%userprofie%\text.txt"` so we don't need this PathFileExists check.

`PathFilesExists()` replaced with `wcslen() > 0`.

**Comment by ProgerXP** [comment] 2020-02-12 19:14
> I found that it only happens if the pathname of the opened file contains any space. For example, open file `c:\a b c.txt`, do Alt+K, Last, OK.

It works now. What was causing this strange problem?

> `PathFilesExists()` replaced with `wcslen() > 0`.

Check these two cases:

1. Shortcut, path = `"%userprofile%\test.txt"`. Doesn't work (worked before).
2. Shortcut, path = `Notepad2e.exe ... "%userprofile%\test.txt"`. Doesn't work.

**Comment by cshnik** [comment] 2020-02-12 20:12
> > I found that it only happens if the pathname of the opened file contains any space. For example, open file `c:\a b c.txt`, do Alt+K, Last, OK.
> 
> It works now. What was causing this strange problem?

Incorrect use of incoming buffer caused unexpected behavior.

> 1. Shortcut, path = `"%userprofile%\test.txt"`. Doesn't work (worked before).

Works for me on Windows 7. Can you show your LNK? Do you run it by double click or directly call Notepad2e from command line?
However I've added the fix for this case: `> Notepad2e.exe "%userprofile%\test.txt.lnk"`
BTW, there is `/expandenv` option which may help in some cases.

> 2. Shortcut, path = `Notepad2e.exe ... "%userprofile%\test.txt"`. Doesn't work.

It looks like the case with incorrect parameters does not refer to this issue and should be fixed separately.

**Closed** 2020-02-13 13:19 UTC
Labels: upcoming release
