### ISSUE TITLE
Does not compile with VS2017

### ISSUE THREAD

**Issue by csware** [ProgerXP/Notepad2e#178] opened 2018-08-10 20:32 UTC
Notepad2e does not compile with VS2017.

There are lots of compile errors and also the project file has hard-coded values which point to old WIndows SDKs.

**Comment by ProgerXP** [comment] 2018-08-10 20:54
@cshnik Look into this issue please.

**Comment by cshnik** [comment] 2018-08-13 18:21
Fixed.
1. Removed specific target SDK (default is OK).
2. Target platform toolset upgraded to "Visual Studio 2017 - Windows XP (v141_xp)".
Switching this option back to "Visual Studio 2015 - Windows XP (v140_xp)" (Notepad2e> Properties> General> Platform Toolset) allow user to rebuild the project in VS2015.

**Comment by csware** [comment] 2018-08-14 07:35
This change is not sufficient - VS still complains about missing precompiled header includes... I have a working version, I'll open a MR soon.

**Comment by csware** [comment] 2018-08-14 08:12
How do you build Notepad2e? Using teh VS2017 IDe or using the wdkbuild batch file?

**Comment by ProgerXP** [comment] 2018-08-14 08:18
> This change is not sufficient - VS still complains about missing precompiled header includes... I have a working version, I'll open a MR soon.

I confirm this. Neither Release nor Debug configurations compile on VS2017:

```
src\extension\base64.c(334, 0): error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "stdafx.h"' to your source?
src\extension\commonutils.c(30, 0): error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "stdafx.h"' to your source?
src\extension\externals.c(109, 0): error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "stdafx.h"' to your source?
src\extension\stringrecoding.c(741, 0): error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "stdafx.h"' to your source?
src\extension\strtobase64.c(47, 0): error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "stdafx.h"' to your source?
src\extension\strtohex.c(122, 0): error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "stdafx.h"' to your source?
src\extension\strtoqp.c(197, 0): error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "stdafx.h"' to your source?
src\extension\tinyexpr\tinyexpr.c(961, 0): error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "stdafx.h"' to your source?
src\extension\trace.c(99, 0): error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "stdafx.h"' to your source?
```

@cshnik Ensure that the project can be built on a clean system with VS2017 or VS2015 from ground up with no errors (possibly requiring some simple switch of the target SDK only).

**Comment by csware** [comment] 2018-08-14 10:57
I have a working version, I'll open a MR soon.

**Comment by csware** [comment] 2018-08-14 16:51
How do you build Notepad2e? Do you use Notepad2.mak (I doubt as this is missing the SCI_OWNREGEX definition), but the VS solution file has other options set (especially some security features are not set; also it optimizes for speed but Notepad2.mak or size)...

**Comment by cshnik** [comment] 2018-08-14 18:16
I was able to reproduce the issue. The point is: there are multiple problems with x64 configurations (since we never tested/used it) and x64 is selected by default on project startup.
At this point, please use x86 configurations to build the project.

**Comment by ProgerXP** [comment] 2018-08-14 18:28
> At this point, please use x86 configurations to build the project.

Bitness doesn't matter, the same compilation errors appear in any configuration - Debug/Release, x86/x64.

**Comment by cshnik** [comment] 2018-08-14 18:32
"precompiled header"-error relates to Notepad2eTests project. Please try to build Notepad2e only. If the problem remains please provide complete build logs.

**Comment by ProgerXP** [comment] 2018-08-14 19:12
Compiling Notepad2e.vcxproj results in 1 warning and 2 errors:

```
[CL] scintilla\win32\platwin.cxx(713, 0): warning C4244: 'return': conversion from 'float' to 'int', possible loss of data
[CL] src\extension\edithelperex.cpp(2, 0): error C1083: Cannot open include file: 'boost/regex.hpp': No such file or directory
[CL] scintilla\boostregex\boostregexsearch.cxx(28, 0): error C1083: Cannot open include file: 'boost/regex.hpp': No such file or directory 
```

**Comment by cshnik** [comment] 2018-08-14 19:16
> [CL] src\extension\edithelperex.cpp(2, 0): error C1083: Cannot open include file: 'boost/regex.hpp': No such file or directory
> [CL] scintilla\boostregex\boostregexsearch.cxx(28, 0): error C1083: Cannot open include file: 'boost/regex.hpp': No such file or directory 

Boost setup is required for regex:
https://github.com/ProgerXP/Notepad2e/blob/master/doc/BoostSetup.md

**Comment by cshnik** [comment] 2018-08-14 20:31
>> How do you build Notepad2e? Do you use Notepad2.mak (I doubt as this is missing the SCI_OWNREGEX definition), but the VS solution file has other options set (especially some security features are not set; also it optimizes for speed but Notepad2.mak or size;; the project uses the runtime MultiThreaded, but the mak file MultiThreadedDLL)...

> Can you please anser #178 (comment)?! I'm trying to optime the project configuration file and I need to know which settings I need to prioritize.

Here are the points:
1. We always use solution to build the project from Visual Studio.
2. Notepad2.mak file had never changed since initial commit.
3. SCI_OWNREGEX define is required to embed custom regex.

**Comment by ProgerXP** [comment] 2018-08-14 20:43
@csware 

> especially some security features are not set

I am interested in what security features are missing? I see no reason to not enable long-present features like ASLR. Can you list them? 

@cshnik Were these settings just taken verbatim from Notepad2?

---

> Check next files created in %BOOST_ROOT%\stage\lib: libboost_regex-vc140-mt-s-1_63.lib libboost_regex-vc140-mt-sgd-1_63.lib

Having built it with VS2017, I see `*-vc141-*` files instead.

The build fails with the same errors - boost files cannot be found. I have %BOOST_ROOT% set and have those lib files after having followed BoostSetup.md.

**Comment by ProgerXP** [comment] 2018-08-14 20:49
Nevermind, I have re-checked and the env variable wasn't set. I managed to build it in Debug mode. Now trying different setups.

@cshnik Still, test compilation should be fixed. Why don't they compile out of the box?

**Comment by cshnik** [comment] 2018-08-14 20:58
> Were these settings just taken verbatim from Notepad2?

N/A

> Having built it with VS2017, I see *-vc141-* files instead.

Correct, v141 is a VS2017 platform toolset. Provided example referenced to VS2015 one.

> Still, test compilation should be fixed. Why don't they compile out of the box?

I've already fixed solution for x64 platform. The only thing is to build x64 boost regex for testing purposes. I've found x64 platform was incorrectly added back in 2016 [9e0d336], commented as "x64 platform added: doesn't compile at the moment;"

**Comment by ProgerXP** [comment] 2018-08-14 21:07
Compiling vcxproj for Release/Debug x86 - works.

For x64 - doesn't:

```
E: [CL] type_traits(94, 0): error C2953: 'std::_Is_function<_Ret(_Types...)>': class template has already been defined
: [CL] type_traits(94): note: see declaration of 'std::_Is_function<_Ret(_Types...)>'
E: [CL] type_traits(94, 0): error C2953: 'std::_Is_function<_Ret(_Types...)>': class template has already been defined
: [CL] type_traits(94): note: see declaration of 'std::_Is_function<_Ret(_Types...)>'
E: [CL] type_traits(94, 0): error C2953: 'std::_Is_function<_Ret(_Types...) const>': class template has already been defined
: [CL] type_traits(94): note: see declaration of 'std::_Is_function<_Ret(_Types...) const>'
...
E: [CL] c:\program files (x86)\microsoft sdks\windows\v7.1a\include\winnt.h(135, 0): error C1189: #error: "No Target Architecture"
```

Any idea why?

**Comment by ProgerXP** [comment] 2018-08-14 21:18
Compiling sln doesn't work, still same errors with missing stdafx inclusion.

**Comment by ProgerXP** [comment] 2018-08-17 09:58
After merging #184, Notepad2e.sln compilation (x86/x64) fails with:

```
test\extension\stdafx.h(11, 0): error C1083: Cannot open include file: 'CppUnitTest.h': No such file or directory
```

Notepad2e.vcxproj compiles fine for x86. For x64, I get errors like this (different for Debug and Release):

```
[CL] c:\program files (x86)\microsoft sdks\windows\v7.1a\include\winnt.h(31, 0): error C1083: Cannot open include file: 'ctype.h': No such file or directory
```

Is something wrong with my build configuration?

**Comment by cshnik** [comment] 2018-08-20 15:41
> Is something wrong with my build configuration?

There are no problems with solution in my configuration: the project properly compiled when testing all available build types.

**Comment by ProgerXP** [comment] 2018-08-21 07:36
I got it compiling with VS2017, Release/Debug x86/x64 of the main project and tests.

From a quick glance, the x64 version doesn't crash.

However, running tests (in Debug/x86 configuration) fails with:

```
File not found: test\Extension\bin\Win32\Debug\..\..\..\test\data\Extension\TestFile1__src_UTF8.txt
```

It looks like the path is not correct since the DLL is inside `test\Extension\bin\Win32\Debug` and it should be 5 `..\` instead of 3.

**Comment by cshnik** [comment] 2018-08-22 19:10
> However, running tests (in Debug/x86 configuration) fails

Cannot reproduce. Please provide complete output if the issue remains.

**Comment by cshnik** [comment] 2018-08-22 19:40
Output directory for Notepad2eTests project is `$(SolutionDir)bin\$(Platform)\$(Configuration)\` which is translated to `bin\Win32\Debug\` (not `test\Extension\bin\Win32\Debug\`).
It looks like there is a problem with your local configuration.
![image](https://user-images.githubusercontent.com/8019354/44486469-df2a1500-a67d-11e8-8c12-4716f040d2fe.png)

**Comment by ProgerXP** [comment] 2018-08-22 20:40
This must be because I'm compiling tests separately from the main solution. When compiling only test/Extension/Notepad2eTests.vcxproj, is SolutionDir set to vcxproj's directory? Can it be made so that it can be compiled and ran separately?

**Comment by csware** [comment] 2018-08-23 07:45
Why not use the main solution? It can also be used for building from cli, cf. https://github.com/TortoiseGit/TortoiseGit/blob/master/appveyor.yml

**Comment by ProgerXP** [comment] 2018-08-23 08:11
I am using a build server. The solution is compiling way longer than just tests alone, so for tests I want to compile their project only. I don't see any msbuild.exe parameter to specify a separate vcxproj file (if you give sln for compilation). 

If not, then a build target should be added to the solution that will compile tests only. It can be ran with `msbuild /T` like in your example.

**Comment by csware** [comment] 2018-08-23 08:14
>  I don't see any msbuild.exe parameter to specify a separate vcxproj file

Please see the link I posted!

**Comment by ProgerXP** [comment] 2018-08-23 08:17
> Please see the link I posted!

I did.

> If not, then a build target should be added to the solution that will compile tests only. It can be ran with msbuild /T **like in your example.**

https://msdn.microsoft.com/en-us/library/ms164311.aspx

> /t:targets
> If you specify any targets by using this switch, they are run instead of any targets in the DefaultTargets attribute in the project file. 

Or are you talking about some other switch?

**Comment by cshnik** [comment] 2018-08-29 16:58
Please follow next steps to build and run Notepad2eTests project:
1. Run "Developer command prompt"
2. Switch to Notepad2e directory, e.g.: 
>  &gt;cd C:\Work\git\Notepad2e
3. Compile Notepad2eTests project only:
> &gt;msbuild Notepad2e.sln /t:Notepad2eTests /p:Configuration="Debug" /p:Platform="x86"
4. Run tests:
> &gt;vstest.console.exe bin\Win32\Debug\Notepad2eTests.dll

**Comment by ProgerXP** [comment] 2018-08-29 20:02
>Notepad2e.sln: error MSB4057: The target "Notepad2eTests" does not exist in the project.

**Comment by ProgerXP** [comment] 2018-08-29 20:16
After some tinkering I got only this project of the solution compiling with MSBuild, but now I get test failures (even when running your command line command manually):

```
i: [VSTest] Notepad2eTests.CEval.EvalTests
i: [VSTest] Notepad2eTests.CStringToQP.TestQP_StringSamples
F: [VSTest] Notepad2eTests.CStringToQP.TestQP_FileSamples
F: [Notepad2eTests.CStringToQP.TestQP_FileSamples] Assert failed. Encoding, UTF-8 encoding, source: TestFile1__src_UTF8.txt
UTF-8 encoding. test\extension\textencodingtests.cpp, DoRecodingTest line 56
F: [Notepad2eTests.CStringToQP.TestQP_FileSamples] at DoRecodingTest() in test\extension\textencodingtests.cpp:line 58
at Notepad2eTests::CStringToQP::TestQP_FileSamples() in test\extension\textencodingtests.cpp:line 175
i: [VSTest] Notepad2eTests.CStringToBase64.TestBase64_StringSamples
F: [VSTest] Notepad2eTests.CStringToBase64.TestBase64_FileSamples
F: [Notepad2eTests.CStringToBase64.TestBase64_FileSamples] Assert failed. Encoding, UTF-8 encoding, source: TestFile1__src_UTF8.txt
UTF-8 encoding. test\extension\textencodingtests.cpp, DoRecodingTest line 56
F: [Notepad2eTests.CStringToBase64.TestBase64_FileSamples] at DoRecodingTest() in test\extension\textencodingtests.cpp:line 58
at Notepad2eTests::CStringToBase64::TestBase64_FileSamples() in test\extension\textencodingtests.cpp:line 147
i: [VSTest] Notepad2eTests.CStringToHex.TestHex_StringSamples
F: [VSTest] Notepad2eTests.CStringToHex.TestHex_FileSamples
F: [Notepad2eTests.CStringToHex.TestHex_FileSamples] Assert failed. Encoding, UTF-8 encoding, source: TestFile1__src_UTF8.txt
UTF-8 encoding. test\extension\textencodingtests.cpp, DoRecodingTest line 56
F: [Notepad2eTests.CStringToHex.TestHex_FileSamples] at DoRecodingTest() in test\extension\textencodingtests.cpp:line 58
at Notepad2eTests::CStringToHex::TestHex_FileSamples() in test\extension\textencodingtests.cpp:line 114
```

**Comment by cshnik** [comment] 2018-08-30 18:17
Please setup environment variable FileSamplesPath before running tests, i.e:
>  &gt;set FileSamplesPath=C:\Work\git\Notepad2e\test\data\Extension
> &gt;vstest.console.exe bin\Win32\Debug\Notepad2eTests.dll

**Comment by ProgerXP** [comment] 2018-08-30 18:46
I still can't get it to work even with manual vstest. The path is correct (checked). Same assertion errors.

**Comment by cshnik** [comment] 2018-08-30 19:00
Your errors look completely different from what I see locally. Here is an output for tests with wrong file samples path, >vstest.console.exe Notepad2e\bin\Win32\Debug\Notepad2eTests.dll:

>Microsoft (R) Test Execution Command Line Tool Version 15.7.2
Copyright (c) Microsoft Corporation.  All rights reserved.
>
>Starting test execution, please wait...
Passed   EvalTests
Passed   TestQP_StringSamples
Failed   TestQP_FileSamples
Error Message:
 Assert failed. File not found: C:\Work\git\Notepad2e\bin\Win32\Debug\D:\TestFile1__src_UTF8.txt. c:\work\git\notepad2e\test\extension\textencodingtestcasedata.cpp, CTestCaseData::LoadFile	line 95
Stack Trace:
	at CTestCaseData::LoadFile() in c:\work\git\notepad2e\test\extension\textencodingtestcasedata.cpp:line 96
	at CTestCaseData::GetSourceText() in c:\work\git\notepad2e\test\extension\textencodingtestcasedata.cpp:line 125
	at DoRecodingTest() in c:\work\git\notepad2e\test\extension\textencodingtests.cpp:line 49
	at Notepad2eTests::CStringToQP::TestQP_FileSamples() in c:\work\git\notepad2e\test\extension\textencodingtests.cpp:line 175
Passed   TestBase64_StringSamples
Failed   TestBase64_FileSamples
Error Message:
 Assert failed. File not found: C:\Work\git\Notepad2e\bin\Win32\Debug\D:\TestFile1__src_UTF8.txt. c:\work\git\notepad2e\test\extension\textencodingtestcasedata.cpp, CTestCaseData::LoadFile	line 95
Stack Trace:
	at CTestCaseData::LoadFile() in c:\work\git\notepad2e\test\extension\textencodingtestcasedata.cpp:line 96
	at CTestCaseData::GetSourceText() in c:\work\git\notepad2e\test\extension\textencodingtestcasedata.cpp:line 125
	at DoRecodingTest() in c:\work\git\notepad2e\test\extension\textencodingtests.cpp:line 49
	at Notepad2eTests::CStringToBase64::TestBase64_FileSamples() in c:\work\git\notepad2e\test\extension\textencodingtests.cpp:line 147
Passed   TestHex_StringSamples
Failed   TestHex_FileSamples
Error Message:
 Assert failed. File not found: C:\Work\git\Notepad2e\bin\Win32\Debug\D:\TestFile1__src_UTF8.txt. c:\work\git\notepad2e\test\extension\textencodingtestcasedata.cpp, CTestCaseData::LoadFile	line 95
Stack Trace:
	at CTestCaseData::LoadFile() in c:\work\git\notepad2e\test\extension\textencodingtestcasedata.cpp:line 96
	at CTestCaseData::GetSourceText() in c:\work\git\notepad2e\test\extension\textencodingtestcasedata.cpp:line 125
	at DoRecodingTest() in c:\work\git\notepad2e\test\extension\textencodingtests.cpp:line 49
	at Notepad2eTests::CStringToHex::TestHex_FileSamples() in c:\work\git\notepad2e\test\extension\textencodingtests.cpp:line 114
>
>Total tests: 7. Passed: 4. Failed: 3. Skipped: 0.
Test execution time: 0.6041 Seconds

Please describe in details your system/project configuration, provide a snapshot for project files and complete output for executed commands.

**Comment by ProgerXP** [comment] 2018-08-30 21:26
> PS At this point it looks like environment variable "FileSamplesPath"was not properly passed to vstest.

I tried checking it in different cases:

1. Via my build server configuration, using `echo test >%FileSamplesPath%\test` - the file is created under `test\data\Extension` which appears to be correct
2. Directly via cmd as per your 2 lines - see this screenshot (particularly the first line with `set`)
![tests](https://user-images.githubusercontent.com/1643195/44880186-66960a80-acb4-11e8-8b47-d18bac435ade.png)
:

**Comment by ProgerXP** [comment] 2018-08-30 21:28
I suggest you add a separate assertion for FileSamplesPath env variable's validity (like a file existance check), to rule out problems in test runner setup, separately from test case failures.

**Comment by cshnik** [comment] 2018-08-31 03:30
I was able to reproduce the issue. Test file samples were not restricted to use standard Windows line endings (CRLF) which caused incorrect binary content when downloaded from github.

**Comment by ProgerXP** [comment] 2018-09-01 17:27
Finally it compiles and all tests pass. Later I will look into removing binaries from this repository and automatically uploading new builds elsewhere.

**Closed by ProgerXP** 2018-09-01 17:27 UTC
