### ISSUE TITLE
Support of compilation with VS2019 (vc142)

### ISSUE THREAD

**Issue by Anton-V-K** [ProgerXP/Notepad2e#383] opened 2021-12-07 08:43 UTC
It's not possible to build the app with VS2019 (vc142), because the project file `Notepad2e.vcxproj` isn't aware of this version:
```
  <PropertyGroup Label="Configuration">
    <ConfigurationType>Application</ConfigurationType>
    <CharacterSet>Unicode</CharacterSet>
    <PlatformToolset Condition="'$(VisualStudioVersion)' == '15.0'">v141_xp</PlatformToolset>
    <PlatformToolset Condition="'$(VisualStudioVersion)' == '14.0'">v140_xp</PlatformToolset>
  </PropertyGroup>
```
The fix may be straightforward - just add the line to the list:
```
    <PlatformToolset Condition="'$(VisualStudioVersion)' == '16.0'">v142_xp</PlatformToolset>
```
Same change may be applied to `Notepad2eTests.vcxproj` as well, and the reference to old SDK may be removed (as it was done in #178): the line `<WindowsTargetPlatformVersion>7.0</WindowsTargetPlatformVersion>` isn't needed any longer.

I would also recommend adding support for locally customizable builds via properties.
It is enough to add line like
```
  <Import Project="User.props" Condition="exists('User.props')" />
```
after `</PropertyGroup>` of the above mentioned fragment, and anyone will be able to build the app with any version of VS/toolset/SDK for own needs.

**Comment by ProgerXP** [comment] 2021-12-07 08:59
Create a pull request with both changes please.

**Comment by Anton-V-K** [comment] 2021-12-08 19:22
It seems `vc142_xp` doesn't exists (see [C++ features deprecated in Visual Studio 2019](https://docs.microsoft.com/en-us/cpp/porting/features-deprecated-in-visual-studio?view=msvc-170)):
> Visual Studio 2019 and later does not include support for creating code for Windows XP by using the v142 toolset. Support for Windows XP development by using the v141 toolset that shipped in Visual Studio 2017 is available as an optional component in the Visual Studio Installer.
So it's not possible to build for Windows XP with VS2019.
Which option should be chosen in the project file for VS2019?
1. `vc142` (no Windows XP support, installed by default in VS2019)
2. `vc141_xp` (should be installed additionally for VS2019)

**Comment by Anton-V-K** [comment] 2021-12-08 23:41
the PR is partially incorrect - `vc142_xp` shouldn't be there. I will replace it with `vc141_xp` or `vc142`

**Comment by ProgerXP** [comment] 2021-12-09 10:55
Let's use `vc141_xp` - I want to be explicit that support for XP is required. If somebody wants to compile Notepad 2e manually, they can retarget for `vc142`. As for you, please use `vc141_xp` to avoid toolset-specific problems between `vc141_xp` (used to compile user builds) and more recent versions.

**Comment by Anton-V-K** [comment] 2021-12-09 15:38
I've replaced `v142_xp` with `v141_xp` for VS2019, and the PR #385 is ready for reviewing/merging

**Comment by ProgerXP** [comment] 2021-12-09 17:18
@cshnik Check #385, if it looks okay then merge it.

**Comment by cshnik** [comment] 2021-12-16 14:00
@Anton-V-K 
Please consider the following:
1. Currently PR contains excess changes (changes within Scintilla sources) which are not required to build project with VS2019 using ``vc141_xp`` toolset.
2. The most simple way to provide compatibility for newer VS versions is (the same for both Notepad2e.vcxproj/Notepad2eTests.vcxproj):
```
<PlatformToolset Condition="'$(VisualStudioVersion)' == '15.0'">v141_xp</PlatformToolset>
```
replace with:
```
<PlatformToolset Condition="'$(VisualStudioVersion)' != '14.0'">v141_xp</PlatformToolset>
```
3. Current change for including ``User.props`` does not work: ``Import Project``-statement is out of ``ImportGroup``-block and it does nothing. It should look like this:
```
  <ImportGroup Label="PropertySheets">
    <Import Project="User.props" Condition="exists('User.props')"/>
  </ImportGroup>
```

**Comment by Anton-V-K** [comment] 2021-12-16 17:00
@cshnik , thanks for the feedback.

1. I thought, the sources under `scintilla\boostregex` aren't part of Scintilla library any more - I can't find them in the [current version 5.1.5](https://www.scintilla.org/ScintillaDownload.html).
I guess, these files were taken from an older version of the library, so conflicts there are unlikely to happen.

2. OK, I will change that.

3. Putting `User.props` inside `ImportGroup` has no extra effect (at least in VS2019): the project builds fine either way, and VS2019 doesn't show the toolset from imported properties (looks like an issue with VS2019).
BTW standard properties are included without extra `ImportGroup`.

**Comment by ProgerXP** [comment] 2021-12-17 18:38
@cshnik I have squashed the PR to allow working on subsequent tasks. But let's determine if there are any remaining issues.

> 1. Currently PR contains excess changes (changes within Scintilla sources) which are not required to build project with VS2019 using `vc141_xp` toolset.

@Anton-V-K  claims that without these changes it's impossible to build using `vc142`. While we're defaulting to `vc141_xp`, there is no reason to prevent people from using the default toolset of VS2019, if they are not interested in XP support. Can you confirm this?

Can you also confirm the 3rd point?

> 1. It looks like the sources under `scintilla\boostregex` aren't part of Scintilla library any more - I can't find them in the [current version 5.1.5](https://www.scintilla.org/ScintillaDownload.html) or in the [maintaned version 3.21.1](https://sourceforge.net/projects/scintilla/files/scintilla/3.21.1/).

This is interesting. Where are they coming from? @cshnik

**Comment by cshnik** [comment] 2021-12-23 18:10
> @Anton-V-K claims that without these changes it's impossible to build using `vc142`. While we're defaulting to `vc141_xp`, there is no reason to prevent people from using the default toolset of VS2019, if they are not interested in XP support. Can you confirm this?

Correct. All these changes are required to build project using `vc142`.
It is a good practice to make project compatible with new VS versions since these are released regularly.
However I see no actual reason why we should patch sources to provide compatibility with new toolset. Moreover there is a chance header compatibility issue will appear (when testing build on newer toolset) which can't be resolved by changing include-s. Strictly speaking, platform toolset is prerequisite for the project and it should not be updated on the regular basis with no reason. Since Notepad2e is ``C``-project and currently used Scintilla's version 3.x is legacy at now days there is no real profit from new platform toolset support.
Current sources are compatible with `vc141`,  `vc141_xp`,  `vc142` and `vc142_xp` toolsets.

> > 1. It looks like the sources under `scintilla\boostregex` aren't part of Scintilla library any more - I can't find them in the [current version 5.1.5](https://www.scintilla.org/ScintillaDownload.html) or in the [maintaned version 3.21.1](https://sourceforge.net/projects/scintilla/files/scintilla/3.21.1/).
> 
> This is interesting. Where are they coming from? @cshnik

https://github.com/ProgerXP/Notepad2e/issues/78#issuecomment-374760672
These files came from ``Notepad++`` and are the custom regex implementation for Scintilla's purposes. All the files under Scintilla folder is anyway the part of this project embedded into Notepad2e.

**Comment by cshnik** [comment] 2021-12-23 20:15
1. Currently User.props is imported but not displayed in the VS Property Manager:
<image width="200" src="https://user-images.githubusercontent.com/8019354/147286690-f4415a88-a6a1-4746-9477-39fdf18bb161.png"/>

2. Adding of parent ```ImportProject``` item in the same place of Notepad2e.vcxproj will break the set of standard properties:
<image width="200" src="https://user-images.githubusercontent.com/8019354/147286695-16ff6072-6d89-4210-9fd5-f1094098384a.png"/>

3. Adding to ```ImportProject``` after the last import of standard ```.props``` will give the correct result:
<image width="200" src="https://user-images.githubusercontent.com/8019354/147286702-c7226e40-a227-43cd-8f39-efc67ee2fcf8.png"/>

4. Platform toolset can't be changed the way it was declared in the currently provided ``User.props`` sample file: https://stackoverflow.com/questions/68226262/how-to-override-a-configuration-level-property-in-a-properties-file. Provided ``.props`` sample should have working customizing example.

**Comment by Anton-V-K** [comment] 2021-12-23 22:32
> Currently User.props is imported but not displayed in the VS Property Manager

Well, the approach worked quite good - it allowed to customize the platform toolset.
I agree it was a kind of hack, so I wouldn't bother myself with modifying these properties through VS UI :)

The approach with `Directory.Build.props` allowing to inject custom properties 'at the right moment' also works fine.
However its main drawback is increased amount of 'support files' - instead of one `User.props.IN` (+ its local copy `User.props`) we will need up to 3-4 files:
- 2 x `Directory.Build.props` (for `Notepad2e.vcxproj` and `Notepad2eTests.vcxproj` which are in different folders)
- ~~`User.props.IN`~~ `Platform.props.IN` + its local copy `Platform.props` (in the solution folder or another fixed location)
Not a big bunch of work anyway.
But in the end you still won't be able to tune toolset version through the Property Manager - [it's by design](https://developercommunity.visualstudio.com/t/overridden-settings-inside-directorybuildprops-or/983193) :)

**Comment by Anton-V-K** [comment] 2021-12-25 08:53
I think, both files can be added as examples - `Directory.Build.props.IN` and `Platform.props.IN`, so they won't affect release builds. With proper instructions (for instance, in comments + link to this issue) anyone will be able to select platform toolset locally for own needs.

**Comment by cshnik** [comment] 2021-12-28 21:35
We've previously agreed we can tie proper/compatible platform toolset with VS version directly in the ``.vcxproj``-file.
Updating of the platform toolset [most likely] always require additional changes in the source code and will not work out-of-box.
Current scheme with ``build_props`` looks complicated (by design) and unclear (by its purpose) because the platform toolset selected via ``.props``-file does not guarantee the project build succeeded.
Why do we need to have an ability to setup platform toolset via custom ``.props``-file?

**Comment by Anton-V-K** [comment] 2021-12-29 14:46
> I see no actual reason why we should patch sources to provide compatibility with new toolset

I've finally managed to add `v141_xp` to my VS2019 (actually I had to re-install VS completely, due to the wierd way VS2019 handles new workloads added to offline cache - see [the issue](https://developercommunity.visualstudio.com/t/cannot-install-v141-xp-for-vs2019-in-offline-mode/1622776)), and can now comment on this.
It seems patching sources is required to build with `v141_xp` in VS2019, because this version comes with new STL headers.
For instance, here is how `vector` (from `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vector`) for VS2019 starts:
```
// vector standard header

// Copyright (c) Microsoft Corporation.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#pragma once
#ifndef _VECTOR_
#define _VECTOR_
#include <yvals_core.h>
#if _STL_COMPILER_PREPROCESSOR
#include <xmemory>

#if _HAS_CXX17
#include <xpolymorphic_allocator.h>
#endif // _HAS_CXX17
```
And here is how `vector` (from `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\vector`) for VS2017 starts:
```
// vector standard header
#pragma once
#ifndef _VECTOR_
#define _VECTOR_
#ifndef RC_INVOKED
#include <xmemory>
#include <stdexcept>

#if _HAS_CXX17
 #include <xpolymorphic_allocator.h>
#endif /* _HAS_CXX17 */
```

Moreover VS2019 shows following warning when building with `v141_xp`:
```
warning MSB8051: Support for targeting Windows XP is deprecated and will not be present in future releases of Visual Studio.
  Please see https://go.microsoft.com/fwlink/?linkid=2023588 for more information.
```
Fortunately the support is still present in VS2022 Community - there is the workload `Microsoft.VisualStudio.Component.WinXP` in the [official list](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community?view=vs-2022).

**Comment by ProgerXP** [comment] 2022-01-18 19:06
@Anton-V-K Regarding this issue overall, I think the project configuration is good at the current form. I don't want to make further changes to support toolset version selection in user props. Other than this, it seems we have incorporated all your suggestions.

> It seems patching sources is required to build with `v141_xp` in VS2019, because this version comes with new STL headers.

Explicit include's of stdexcept were added in #385 and are part of the codebase. The project builds fine in VS2019 with all 3 toolsets (141/142/xp), does it not?

**Comment by Anton-V-K** [comment] 2022-01-19 22:24
> The project builds fine in VS2019 with all 3 toolsets (141/142/xp), does it not?

Yes, it is possible to build current code with VS2019 (`v141_xp`).
Other toolset (if needed) can be selected using the approach based on `Directory.Build.props`. This hint may be added to README, so it will be easily discoverable.

**Closed** 2022-01-20 08:20 UTC
